### ISSUE TITLE
Priority: high | Adding easy User selection when creating new package in APP

### ISSUE THREAD

**Issue by alexkrsn** [DuratarskeyK/wooproxy-auth#13]
I thought you introduced that earlier but I no longer see this. When creating a new package manually, the users are not sorted alphabetically, I spend a lot of time finding the correct user to assign. Please either introduce alphabetic order or create a search box as in API.

**Comment by DuratarskeyK** [comment]
Sorry, the gem update broke this, should be fixed now.
