### ISSUE TITLE
Priority: medium | "Reason for cancellation" pop-up

### ISSUE THREAD

**Issue by alexkrsn** [DuratarskeyK/wooproxy-auth#5]
Reason for cancellation pop-up where the client is required to type his reason for cancellation after canceling the package.

**Comment by DuratarskeyK** [comment]
Done

**Comment by alexkrsn** [comment]
Please make it mandatory

**Comment by DuratarskeyK** [comment]
Done

**Comment by alexkrsn** [comment]
Либо ещё один pop-up перед reason for cancellation, либо в ту же форму нужен tickbox

текст:

If the proxies do not work as intended please consider swapping them before cancellation. Our experts can solve your problem or provide a replacement. 

To do that, please contact our team through the chat at the bottom right corner of this page.

tickbox:

I don't need a replacement! Please just cancel

**Comment by alexkrsn** [comment]
можно поднять tick box над reason for cancellation и Package ID и под текст с ним связанный?

Текст лучше не делать таким слипшимся - сделай расстояние между предложениями типа <br>.

Там опечатка: at the bottom left corner. Нужно сделать RIGHT corner

**Comment by DuratarskeyK** [comment]
Done
